### ISSUE TITLE
Read/write Zooma

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/ebispot.github.io#16]
Zoom requires access to curated mapping to optimise the annotation prediction algorithm. Currently we only have a few groups providing mappings, that must come via spreadsheets and have around a 1-2 week turnaround. We will provide a new Zooma with read/write ability to open up the curation to a wider audience and make it easier for external users to provide and manage their mappings via Zooma.

**Comment by simonjupp** [comment]
- [ ] Get instance up and running on scrappy 
- [ ] Load existing mappings from PDX 
- [ ] design extension to scoring algorithm to support additional context
